# Generated by Django 3.1.4 on 2020-12-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geekbang',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('n_start', models.IntegerField(blank=True, null=True)),
                ('short', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('movietitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'geekbang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moviebang',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('n_start', models.IntegerField(blank=True, null=True)),
                ('short', models.CharField(blank=True, max_length=10000, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
                ('movietitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'moviebang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('n_star', models.IntegerField()),
                ('short', models.CharField(max_length=400)),
                ('sentiment', models.FloatField()),
            ],
            options={
                'db_table': 't1',
                'managed': False,
            },
        ),
    ]
