# Generated by Django 3.1.4 on 2020-12-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crabdouban', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geekbang',
        ),
        migrations.DeleteModel(
            name='T1',
        ),
    ]
